#!/usr/bin/env bash
# verify_weaponset_gate.sh — shipped-build WEAPON-SET tier-contrast lineup capture gate (ticket 86caju052 —
# the CI wiring follow-up Tess flagged on PR #254 / 86cajkk7h; the 8-weapon stone+iron set integration).
# Sibling of verify_loot_gate.sh / verify_settings_gate.sh / capture_gate.sh, purpose-built for the
# weapon-family look success-test ("the stone + iron tier lineup reads as ONE cohesive faceted family on the
# shared Mat_WeaponPalette in the SHIPPED build" — faceted shading + shared palette + edge-bevel + the
# stone-vs-iron tier contrast, not just a Blender render). The lineup capture (WeaponSetVerifyCapture.cs,
# exists on main since #254) was until now produced MANUALLY by the orchestrator — it was NEVER a CI gate
# (grep -rn verifyWeaponSet .github/workflows/ → zero hits before this), so a regression in the weapon-pack
# generation / shared-material wiring / import chain could slip straight through GREEN CI. The generic CI
# -captureGate (step 7) only shoots the DEFAULT SPAWN frame — it never frames the weapon lineup at all.
#
# This launches the BUILT exe WINDOWED with -verifyWeaponSet, which drives WeaponSetVerifyCapture: load the
# self-contained Resources/WeaponSetLineup prefab (the stone+iron weapons in a row, shared palette material —
# regenerated by WeaponPackAssetGen.PrepareWeaponPack() at bootstrap), park a post-enabled capture camera
# framing the whole family via the deterministic VerifyCaptureFraming math, and capture weapon_set.png from
# the shipped player. The component calls Application.Quit(1) if the prefab is missing (WeaponPackAssetGen
# never ran) or the bounds never settle, else Quit(0) — so the exe's exit code IS the gate verdict. This
# wrapper launches it windowed and propagates that, with a frame_check.py backstop on the PNG (a real
# swapchain frame, not black/uniform/magenta — the editor-vs-runtime divergence backstop).
#
# Windowed (NOT -batchmode — WeaponSetVerifyCapture uses ScreenCapture.CaptureScreenshot + WaitForEndOfFrame,
# both DEAD under -batchmode: no swapchain to read + no end-of-frame render pass to resume the coroutine —
# spike iter-4 / unity-conventions.md §Headless. This gate CANNOT convert to the 86cag93zb headless
# RT-readback path without a component rewrite; it stays on the pinned runner-1 capture lane with the other
# windowed gates). WEDGE HARDENING (86cafzaeb; mirrors capture_gate.sh / verify_loot_gate.sh): LAUNCH_TIMEOUT
# 300, `timeout -k 15` SIGKILLs a SIGTERM-ignoring hung player, and a single rc==124-only retry re-launches
# ONCE on a first-frame present-loop wedge before declaring failure (a real non-zero gate failure is NEVER
# retried — it would mask a genuine weapon-family regression).
#
# Usage: verify_weaponset_gate.sh <FarHorizon.exe> [<captureDir>] [<logFile>]
#   captureDir default: ci-out/weaponset-caps   logFile default: ci-out/verify-weaponset.log
set -uo pipefail

EXE="${1:-}"
CAP_DIR="${2:-ci-out/weaponset-caps}"
LOG_FILE="${3:-ci-out/verify-weaponset.log}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [ -z "$EXE" ]; then
  echo "usage: verify_weaponset_gate.sh <FarHorizon.exe> [captureDir] [logFile]" >&2
  exit 2
fi
if [ ! -f "$EXE" ]; then
  echo "[verify_weaponset] FAILED — exe not found: $EXE" >&2
  echo "[verify_weaponset]   the build step must run first (FarHorizonBuilder.BuildWindows)" >&2
  exit 1
fi

mkdir -p "$CAP_DIR"
ABS_CAP="$(cd "$CAP_DIR" && pwd)"
mkdir -p "$(dirname "$LOG_FILE")"

# Wall-clock cap so a hung launch fails instead of blocking CI forever. WEDGE HARDENING (86cafzaeb; adopts
# #189's capture_gate/pond pattern): 300 gives real margin over the longest healthy launch. `-k 15`
# hard-KILLs (SIGKILL) a player that ignores the soft SIGTERM 15s later so a wedged D3D12 present-loop
# process can't linger into the retry / the next gate.
LAUNCH_TIMEOUT=300

# launch_once — clear stale artifacts, launch the windowed exe under timeout, set exe_rc.
# Re-clears EVERY attempt so a partial first-attempt capture/log can't mask the retry.
launch_once() {
  rm -f "$ABS_CAP"/weapon_set*.png
  rm -f "$LOG_FILE"
  echo "[verify_weaponset] launching shipped exe windowed (-verifyWeaponSet): $EXE"
  echo "[verify_weaponset]   captureDir=$ABS_CAP logFile=$LOG_FILE"
  # Windowed + small so it never grabs the desktop; -verifyWeaponSet drives WeaponSetVerifyCapture;
  # -logFile redirects the standalone player's Player.log so the capture verdict lines are grep-able here.
  # The component calls Application.Quit(0/1) when done.
  set +e
  timeout -k 15 "${LAUNCH_TIMEOUT}" "$EXE" \
    -screen-fullscreen 0 -screen-width 1280 -screen-height 720 \
    -verifyWeaponSet -captureDir "$ABS_CAP" -logFile "$LOG_FILE"
  exe_rc=$?
  set -e
}

launch_once
# ONE retry, ONLY on a timeout-hang (rc 124 = the first-frame present-loop wedge). A real non-zero
# self-assert failure is NOT a wedge — never retry it (it would mask a genuine weapon-family regression).
if [ "$exe_rc" -eq 124 ]; then
  echo "[verify_weaponset] WARN — exe did not self-quit within ${LAUNCH_TIMEOUT}s (timeout-hang; likely the present-loop wedge) — retrying ONCE" >&2
  launch_once
fi
if [ "$exe_rc" -eq 124 ]; then
  echo "[verify_weaponset] FAILED — exe did not self-quit within ${LAUNCH_TIMEOUT}s (hung launch, including the retry)" >&2
fi

# Echo the component's ground-truth verdict line(s) for the CI log.
if [ -f "$LOG_FILE" ]; then
  grep -F "[WeaponSetVerifyCapture]" "$LOG_FILE" | sed 's/^/[verify_weaponset]   /' || true
fi

# Check 1 — the exit code IS the gate. The component self-asserts the lineup prefab loaded + its bounds
# settled (else Quit(1)). A non-zero exe_rc means Resources/WeaponSetLineup was missing (WeaponPackAssetGen
# never regenerated it at bootstrap) OR the lineup bounds never settled (broken import / empty prefab).
exe_gate_rc=0
if [ "$exe_rc" -ne 0 ]; then
  echo "[verify_weaponset] FAILED — -verifyWeaponSet self-assert reported the lineup prefab was missing or its bounds never settled (exe_rc=$exe_rc)" >&2
  exe_gate_rc=1
fi

# Check 2 — frame backstop: the weapon-set frame must be real swapchain content (not black/uniform/magenta —
# the last would be a shader-strip regression on the shared palette material). One frame expected
# (weapon_set.png); require >= 1.
set +e
python3 "$HERE/frame_check.py" "$ABS_CAP" --min-frames 1
frame_rc=$?
set -e

if [ "$exe_gate_rc" -ne 0 ] || [ "$frame_rc" -ne 0 ]; then
  echo "[verify_weaponset] WEAPON-SET CAPTURE GATE FAILED (exe_rc=$exe_rc frame_rc=$frame_rc)" >&2
  exit 1
fi
echo "[verify_weaponset] WEAPON-SET CAPTURE GATE PASSED — the stone+iron tier lineup renders as one faceted family on the shared palette in the shipped build"
exit 0
